# .azure/deployment.yml
parameters:
  - name: environment
    type: string
    default: "development"

jobs:
  - job: Deploy
    steps:
      - task: DockerCompose@0
        inputs:
          containerregistrytype: "Azure Container Registry"
          azureSubscription: $(AZURE_SUBSCRIPTION)
          azureContainerRegistry: $(ACR_NAME)
          dockerComposeFile: "docker-compose.$(environment).yml"
          action: "Build services"
          projectName: $(Build.Repository.Name)
          qualifyImageNames: true
          additionalImageTags: |
            $(Build.BuildId)
            latest

      - task: AzureContainerApps@1
        inputs:
          azureSubscription: $(AZURE_SUBSCRIPTION)
          resourceGroup: $(RESOURCE_GROUP)
          containerAppName: "bartype-$(environment)"
          containerAppEnvironment: $(CONTAINER_ENV)
          targetPort: 3000
          ingress: "external"
          containerImage: $(ACR_NAME).azurecr.io/bartype-frontend:$(Build.BuildId)
          envVars: |
            NODE_ENV=$(environment)
